(function(){
var stage=document.querySelector('#stage'),fx=document.querySelector('#fx'),ctx=fx.getContext('2d'),robotWrap=document.querySelector('#robotWrap'),robot=document.querySelector('#robot'),head=document.querySelector('#head'),eyes=Array.from(document.querySelectorAll('.eye')),reactions=document.querySelector('#reactionLayer'),hint=document.querySelector('#hint'),soundToggle=document.querySelector('#soundToggle');
var audioCtx=null,muted=false,orientationStarted=false,wakeLock=null,primaryId=null,down=null,moved=false,holdTimer=null,lastInteraction=performance.now();
var pointers=new Map(),ripples=[],trails=[],sparks=[];
function resize(){var d=Math.min(devicePixelRatio||1,2),r=fx.getBoundingClientRect();fx.width=Math.floor(r.width*d);fx.height=Math.floor(r.height*d);ctx.setTransform(d,0,0,d,0,0)}
function ping(x,y,power){power=power||1;ripples.push({x:x,y:y,r:4,a:1,s:2.4*power,p:power});for(var i=0;i<10*power;i++)sparks.push({x:x,y:y,vx:(Math.random()-.5)*4*power,vy:(Math.random()-.5)*4*power,life:1,size:1+Math.random()*2})}
function trail(x,y){trails.push({x:x,y:y,life:1,size:4+Math.random()*4});if(trails.length>90)trails.shift()}
function react(symbol,x,y){x=x||68;y=y||22;var el=document.createElement('span');el.className='reaction';el.textContent=symbol;el.style.setProperty('--x',x+'%');el.style.setProperty('--y',y+'%');reactions.appendChild(el);setTimeout(function(){el.remove()},1300)}
function mark(){lastInteraction=performance.now();hint.classList.add('hide')}
function audio(){if(!audioCtx)audioCtx=new (window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==='suspended')audioCtx.resume()}
function beep(kind){kind=kind||'tap';if(muted)return;audio();var o=audioCtx.createOscillator(),g=audioCtx.createGain(),now=audioCtx.currentTime,f={tap:540,drag:690,special:330,multi:420}[kind]||540;o.type=kind==='special'?'triangle':'sine';o.frequency.setValueAtTime(f,now);if(kind==='special')o.frequency.exponentialRampToValueAtTime(900,now+.35);g.gain.setValueAtTime(.0001,now);g.gain.exponentialRampToValueAtTime(.06,now+.015);g.gain.exponentialRampToValueAtTime(.0001,now+(kind==='special'?.45:.12));o.connect(g).connect(audioCtx.destination);o.start(now);o.stop(now+(kind==='special'?.48:.14))}
soundToggle.addEventListener('click',function(e){e.stopPropagation();muted=!muted;soundToggle.classList.toggle('muted',muted);if(!muted)beep()});
function follow(x,y){var r=stage.getBoundingClientRect(),nx=x/r.width-.5,ny=y/r.height-.5;robotWrap.style.setProperty('--rx',(nx*56)+'px');robotWrap.style.setProperty('--ry',(ny*28)+'px');robotWrap.style.setProperty('--rot',(nx*8)+'deg');head.style.transform='rotate('+(nx*9)+'deg) translate('+(nx*4)+'px,'+(ny*3)+'px)';eyes.forEach(function(e){e.style.transform='translate('+(nx*8)+'px,'+(ny*5)+'px)'})}
function reset(delay){function go(){robotWrap.style.setProperty('--rx','0px');robotWrap.style.setProperty('--ry','0px');robotWrap.style.setProperty('--rot','0deg');robotWrap.classList.remove('dragging');head.style.transform='';eyes.forEach(function(e){e.style.transform=''})}delay?setTimeout(go,140):go()}
function flash(cls,ms){robotWrap.classList.remove('headTap','bodyTap','highFive','special');void robot.getBoundingClientRect();robotWrap.classList.add(cls);setTimeout(function(){robotWrap.classList.remove(cls)},ms)}
function partAt(x,y){var el=document.elementFromPoint(x,y),t=el&&el.closest?el.closest('[data-part]'):null;return t&&t.dataset.part?t.dataset.part:'space'}
function tap(x,y){ping(x,y,1);var part=partAt(x,y);if(part==='head'){flash('headTap',700);react(Math.random()>.5?'💙':'✦',65,19)}else if(part==='hand'){flash('highFive',760);react('✋',74,34)}else if(part==='body'){flash('bodyTap',620);react(Math.random()>.5?'!':'✦',70,24)}else{follow(x,y);react(Math.random()>.5?'?':'✦',67,20);setTimeout(function(){reset(true)},420)}beep('tap');if(navigator.vibrate)navigator.vibrate(12)}
function special(x,y){ping(x,y,2);flash('special',1250);react('💙',56,12);react('✦',77,28);for(var i=1;i<4;i++)(function(j){setTimeout(function(){ping(x,y,1.2)},j*120)})(i);beep('special');if(navigator.vibrate)navigator.vibrate([20,35,28])}
async function orientation(){if(orientationStarted)return;orientationStarted=true;try{if(window.DeviceOrientationEvent&&typeof DeviceOrientationEvent.requestPermission==='function'){var result=await DeviceOrientationEvent.requestPermission();if(result!=='granted')return}window.addEventListener('deviceorientation',function(e){var g=Math.max(-24,Math.min(24,e.gamma||0)),b=Math.max(-24,Math.min(24,(e.beta||0)-45));stage.style.setProperty('--px',(g*-.24)+'px');stage.style.setProperty('--py',(b*-.16)+'px')},{passive:true})}catch(e){}}
async function wake(){if(!('wakeLock' in navigator)||wakeLock)return;try{wakeLock=await navigator.wakeLock.request('screen')}catch(e){}}
stage.addEventListener('pointerdown',function(e){if(e.target.closest&&e.target.closest('#soundToggle'))return;if(stage.setPointerCapture)stage.setPointerCapture(e.pointerId);pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});mark();orientation();wake();audio();if(pointers.size>=2){clearTimeout(holdTimer);robotWrap.classList.add('multi');var ps=Array.from(pointers.values()),mx=ps.reduce(function(a,p){return a+p.x},0)/ps.length,my=ps.reduce(function(a,p){return a+p.y},0)/ps.length;ping(mx,my,1.8);beep('multi');return}primaryId=e.pointerId;down={x:e.clientX,y:e.clientY,t:performance.now()};moved=false;holdTimer=setTimeout(function(){if(!moved&&pointers.has(e.pointerId)){special(e.clientX,e.clientY);pointers.get(e.pointerId).special=true}},680)},{passive:false});
stage.addEventListener('pointermove',function(e){var p=pointers.get(e.pointerId);if(!p)return;p.x=e.clientX;p.y=e.clientY;if(primaryId===e.pointerId&&down&&Math.hypot(e.clientX-down.x,e.clientY-down.y)>8){moved=true;clearTimeout(holdTimer);robotWrap.classList.add('dragging');follow(e.clientX,e.clientY);trail(e.clientX,e.clientY);if(Math.random()<.06)beep('drag')}if(pointers.size>=2){var ps=Array.from(pointers.values()),mx=ps.reduce(function(a,q){return a+q.x},0)/ps.length,my=ps.reduce(function(a,q){return a+q.y},0)/ps.length;follow(mx,my);trail(mx,my)}mark()},{passive:false});
function end(e){var p=pointers.get(e.pointerId);if(!p)return;clearTimeout(holdTimer);var duration=down?performance.now()-down.t:999,pSpecial=!!p.special;pointers.delete(e.pointerId);if(pointers.size<2)robotWrap.classList.remove('multi');if(e.pointerId===primaryId){if(!moved&&!pSpecial&&duration<650)tap(e.clientX,e.clientY);reset(true);primaryId=null;down=null}if(!pointers.size)reset(true);mark()}
stage.addEventListener('pointerup',end,{passive:false});stage.addEventListener('pointercancel',end,{passive:false});stage.addEventListener('contextmenu',function(e){e.preventDefault()});
function draw(){var w=fx.clientWidth,h=fx.clientHeight;ctx.clearRect(0,0,w,h);for(var i=ripples.length-1;i>=0;i--){var q=ripples[i];q.r+=q.s;q.a*=.963;ctx.strokeStyle='rgba(89,232,255,'+q.a+')';ctx.lineWidth=Math.max(1,1.6*q.p);ctx.shadowBlur=18;ctx.shadowColor='#2de5ff';ctx.beginPath();ctx.arc(q.x,q.y,q.r,0,Math.PI*2);ctx.stroke();if(q.a<.035||q.r>190*q.p)ripples.splice(i,1)}for(var j=trails.length-1;j>=0;j--){var t=trails[j];t.life*=.92;ctx.fillStyle='rgba(55,220,255,'+(t.life*.65)+')';ctx.beginPath();ctx.arc(t.x,t.y,t.size*t.life,0,Math.PI*2);ctx.fill();if(t.life<.05)trails.splice(j,1)}for(var k=sparks.length-1;k>=0;k--){var s=sparks[k];s.x+=s.vx;s.y+=s.vy;s.vx*=.98;s.vy*=.98;s.life*=.95;ctx.fillStyle='rgba(130,243,255,'+s.life+')';ctx.beginPath();ctx.arc(s.x,s.y,s.size*s.life,0,Math.PI*2);ctx.fill();if(s.life<.04)sparks.splice(k,1)}ctx.shadowBlur=0;if(performance.now()-lastInteraction>6500&&!pointers.size&&Math.random()<.003)ping(w*(.36+Math.random()*.28),h*(.24+Math.random()*.28),.55);requestAnimationFrame(draw)}
window.addEventListener('resize',resize,{passive:true});window.addEventListener('orientationchange',function(){setTimeout(resize,180)},{passive:true});document.addEventListener('visibilitychange',function(){if(document.visibilityState==='visible'){resize();if(wakeLock&&wakeLock.released)wakeLock=null}});resize();draw();if('serviceWorker' in navigator)window.addEventListener('load',function(){navigator.serviceWorker.register('./sw.js').catch(function(){})});
})();